### ISSUE TITLE
Enter doesn't take you into the function

### ISSUE THREAD

**Issue by KristofferC** [oxinabox/MagneticReadHead.jl#59]
Instead you get to this state:

```
Breakpoint Hit: (::getfield(Main, Symbol("##19#20")))() in Main at /Users/kristoffer/.julia/packages/MagneticReadHead/EjaBR/src/MagneticReadHead.jl:67
         iron_debug(ctx) do
             ctx.metadata.stepping_mode = StepIn
➧            $(esc(body))
         end
     end

Vars: #temp#
Commands: CC (Continue), SI (Step In), SN (Step Next), SO (Step Out), XX (Abort)
```

**Comment by oxinabox** [comment]
yep, this is a thing.
I'm yet to work out a clean way to do it.
Because it is breaking on the first function call after `@enter`,
it is just that that function call happens to be before the function you are support to be entering.

Possibly the simplest would be a bit of a hack that just disallowed breaking inside MagneticReadHead.
The other options like working out what is the actual function and setting a breakpoint there, once,
are annoying.
